---
project: deblur_gan
experiment_desc: fpn

resume:
  resume_training: no
  resume_epoch: 0

train:
  phase: train
  files_a0: data/TRAIN/GOPRO_Large/*/blur/*.png
  files_a1: data/TRAIN/GOPRO_Large/*/blur_gamma/*.png
  files_a2: data/TRAIN/quantitative_datasets/*/input/*.jpg
  files_b0: data/TRAIN/GOPRO_Large/*/sharp/*.png
  files_b1: data/TRAIN/GOPRO_Large/*/sharp/*.png
  files_b2: data/TRAIN/quantitative_datasets/*/GT/*.jpg
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, 1]
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  phase: val
  files_a0: data/TEST/GOPRO_Large/*/blur/*.png
  files_a1: data/TEST/GOPRO_Large/*/blur_gamma/*.png
  files_b0: data/TEST/GOPRO_Large/*/sharp/*.png
  files_b1: data/TEST/GOPRO_Large/*/sharp/*.png
  model_path: fpn_inception.h5
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [0, 1]
  corrupt: *CORRUPT

#phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.01
  disc_loss: ragan-ls
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 300
train_batches_per_epoch: 250
val_batches_per_epoch: 50
batch_size: 6
image_size: [256, 256]

optimizer:
  name: adam
  lr_G: 0.0001
  lr_D: 0.0005

scheduler:
  name: linear
  start_epoch: 20
  min_lr_G: 0.0000001
  min_lr_D: 0.0000005
